version: "3.1"
services:
  reverse-proxy:
    image: nginx:1.17.10
    container_name: reverse-proxy
    depends_on:
      - db
      - api
    ports:
      - 80:80
    networks:
      - app

  db:
    image: postgres
    container_name: db
    restart: always
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nodeapi
      PGDATA: /var/lib/postgresql/data
    networks:
      - app

  api:
    image: node:latest
    container_name: api
    restart: always
    ports:
      - 8080:8080
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    environment:
      - NODE_ENV=production
    command: npm start
    logging:
      options:
        max-size: "8m"
        max-file: "6"
    networks:
      - app

networks:
  app:
    driver: bridge